/****************************************************************************
 *  Copyright (C) 2022 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/
#ifndef __HCI_ERROR_H__
#define __HCI_ERROR_H__

typedef enum {
    HCI_SUCCESS = 0x00,
    HCI_ERR_UNKNOWN_HCI_COMMAND = 0x01,
    HCI_ERR_UNKNOWN_CONNECTION_IDENTIFIER = 0x02,
    HCI_ERR_HARDWARE_FAILURE = 0x03,
    HCI_ERR_PAGE_TIMEOUT = 0x04,
    HCI_ERR_AUTHENTICATION_FAILURE = 0x05,
    HCI_ERR_PIN_OR_KEY_MISSING = 0x06,
    HCI_ERR_MEMORY_CAPACITY_EXCEEDED = 0x07,
    HCI_ERR_CONNECTION_TIMEOUT = 0x08,
    HCI_ERR_CONNECTION_LIMIT_EXCEEDED = 0x09,
    HCI_ERR_SYNCHRONOUS_CONNECTION_LIMIT_TO_A_DEVICE_EXCEEDED = 0x0a,
    HCI_ERR_ACL_CONNECTION_ALREADY_EXISTS = 0x0b,
    HCI_ERR_COMMAND_DISALLOWED = 0x0c,
    HCI_ERR_CONNECTION_REJECTED_LIMITED_RESOURCES = 0x0d,
    HCI_ERR_CONNECTION_REJECTED_SECURITY_REASONS = 0x0e,
    HCI_ERR_CONNECTION_REJECTED_UNACCEPTABLE_BD_ADDR = 0x0f,
    HCI_ERR_CONNECTION_ACCEPT_TIMEOUT_EXCEEDED = 0x10,
    HCI_ERR_UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE = 0x11,
    HCI_ERR_INVALID_HCI_COMMAND_PARAMETERS = 0x12,
    HCI_ERR_REMOTE_USER_TERMINATED_CONNECTION = 0x13,
    HCI_ERR_REMOTE_TERMINATED_CONNECTION_LOW_RESOURCES = 0x14,
    HCI_ERR_REMOTE_TERMINATED_CONNECTION_POWER_OFF = 0x15,
    HCI_ERR_CONNECTION_TERMINATED_BY_LOCAL_HOST = 0x16,
    HCI_ERR_REPEATED_ATTEMPTS = 0x17,
    HCI_ERR_PAIRING_NOT_ALLOWED = 0x18,
    HCI_ERR_UNKNOWN_LMP_PDU = 0x19,
    HCI_ERR_UNSUPPORTED_REMOTE_OR_LMP_FEATURE = 0x1a,
    HCI_ERR_SCO_OFFSET_REJECTED = 0x1b,
    HCI_ERR_SCO_INTERVAL_REJECTED = 0x1c,
    HCI_ERR_SCO_AIR_MODE_REJECTED = 0x1d,
    HCI_ERR_INVALID_LMP_PARAMETERS = 0x1e,
    HCI_ERR_UNSPECIFIED_ERROR = 0x1f,
    HCI_ERR_UNSUPPORTED_LMP_PARAMETER_VALUE = 0x20,
    HCI_ERR_ROLE_CHANGE_NOT_ALLOWED = 0x21,
    HCI_ERR_LMP_OR_LL_RESPONSE_TIMEOUT = 0x22,
    HCI_ERR_LMP_ERROR_TRANSACTION_COLLISION = 0x23,
    HCI_ERR_LMP_PDU_NOT_ALLOWED = 0x24,
    HCI_ERR_ENCRYPTION_MODE_NOT_ACCEPTABLE = 0x25,
    HCI_ERR_LINK_KEY_CANNOT_BE_CHANGED = 0x26,
    HCI_ERR_REQUESTED_QOS_NOT_SUPPORTED = 0x27,
    HCI_ERR_INSTANT_PASSED = 0x28,
    HCI_ERR_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 0x29,
    HCI_ERR_DIFFERENT_TRANSACTION_COLLISION = 0x2a,
    HCI_ERR_QOS_UNACCEPTABLE_PARAMETER = 0x2c,
    HCI_ERR_QOS_REJECTED = 0x2d,
    HCI_ERR_CHANNEL_ASSESSMENT_NOT_SUPPORTED = 0x2e,
    HCI_ERR_INSUFFICIENT_SECURITY = 0x2f,
    HCI_ERR_PARAMETER_OUT_OF_MANDATORY_RANGE = 0x30,
    HCI_ERR_ROLE_SWITCH_PENDING = 0x32,
    HCI_ERR_RESERVED_SLOT_VIOLATION = 0x34,
    HCI_ERR_ROLE_SWITCH_FAILED = 0x35,
    HCI_ERR_EXTENDED_INQUIRY_RESPONSE_TOO_LARGE = 0x36,
    HCI_ERR_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST = 0x37,
    HCI_ERR_HOST_BUSY_PAIRING = 0x38,
    HCI_ERR_CONNECTION_REJECTED_NO_SUITABLE_CHANNEL_FOUND = 0x39,
    HCI_ERR_CONTROLLER_BUSY = 0x3a,
    HCI_ERR_UNACCEPTABLE_CONNECTION_PARAMETERS = 0x3b,
    HCI_ERR_DIRECTED_ADVERTISING_TIMEOUT = 0x3c,
    HCI_ERR_CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE = 0x3d,
    HCI_ERR_CONNECTION_FAILED_TO_BE_ESTABLISHED = 0x3e,
    HCI_ERR_MAC_CONNECTION_FAILED = 0x3f,
    HCI_ERR_COARSE_CLOCK_ADJUSTMENT_REJECTED_BUT_WILL_TRY_TO_ADJUST_USING_CLOCK_DRAGGING = 0x40,
    HCI_ERR_TYPE0_SUBMAP_NOT_DEFINED = 0x41,
    HCI_ERR_UNKNOWN_ADVERTISING_IDENTIFIER = 0x42,
    HCI_ERR_LIMIT_REACHED = 0x43,
    HCI_ERR_OPERATION_CANCELLED_BY_HOST = 0x44,
    HCI_ERR_PACKET_TOO_LONG = 0x45
} hci_error_t;

#endif /* __HCI_ERROR_H__ */